package com.seg;

public enum Configuration {
	VISUAL_REQUIRED,
	VISUAL_DESIRABLE,
	NONPRECISION_REQUIRED,
	NONPRECISION_DESIRABLE,
	CATI_REQUIRED,
	CATI_DESIRABLE,
	CATII_REQUIRED,
	CATII_DESIRABLE,
	CATIIIA_REQUIRED,
	CATIIIA_DESIRABLE,
	CATIIIB_REQUIRED,
	CATIIIB_DESIRABLE,
	CATIIIC_REQUIRED,
	CATIIIC_DESIRABLE,
}
